<?xml version="1.0" encoding="UTF-8" ?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="razbot">
<!--Developed by Shubhankar Das a.k.a Razbotics-->

	<!-- parameters -->
	<xacro:property name="pi" value="3.1415926535897931" />
	<xacro:property name="body_length_x" value="0.294" />
	<xacro:property name="body_length_y" value="0.340" />
	<xacro:property name="coxa_length" value="0.052" />
	<xacro:property name="femur_length" value="0.065" />
	<xacro:property name="tibia_length" value="0.133" />
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/razbot</robotNamespace>
        </plugin>
    </gazebo>

    <link name="base_link"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link" />
        <child link="body_link" />
        <origin xyz="0.0 0.0 0.024" rpy="0.0 0.0 0.0" />
    </joint>

	<link name="body_link">
			<visual>
	  			<origin	xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      			<geometry>
        			<mesh filename="package://hexapod_description/meshes/razbot/body.stl" scale="0.001 0.001 0.001"/>
      			</geometry>
				<material name="">
					<color rgba="0.7 0.7 0.7 1" />
				</material>
			</visual>
			<collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://hexapod_description/meshes/razbot/body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="">
                <color rgba="0.7 0.7 0.7 1"/>
            </material>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.00001"/>
            <inertia
                ixx="1.0" ixy="0.0"  ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
        </inertial>
    </link>
    <gazebo reference="body_link">
        <material>Gazebo/DarkGrey</material>
    </gazebo>

		<!-- Camera properties -->
    <joint name="camera_rgb_joint" type="fixed">
        <parent link="body_link"/>
        <child link="camera_rgb_optical_frame"/>
        <origin xyz="0.05 -0.015 0.099" rpy="${pi/2} ${pi} ${pi/2}"/>
    </joint>
    <link name="camera_rgb_optical_frame">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.00001"/>
            <inertia
                ixx="1.0" ixy="0.0"  ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
        </inertial>
    </link>

    <joint name="camera_depth_joint" type="fixed">
        <parent link="body_link"/>
        <child link="camera_depth_optical_frame"/>
        <origin xyz="0.05 0.015 0.099" rpy="${pi/2} ${pi} ${pi/2}"/>
    </joint>
    <link name="camera_depth_optical_frame">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.00001"/>
            <inertia
                ixx="1.0" ixy="0.0"  ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
        </inertial>
		</link>

	<!-- IMU properties -->
	<joint name="imu_joint" type="fixed">
		<parent link="body_link" />
		<child link="imu_link" />
		<origin xyz="0.0 0.0 0.021" rpy="0.0 0.0 -${pi/2}" />
	</joint>
	<link name="imu_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.00001"/>
            <inertia
                ixx="1.0" ixy="0.0"  ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
        </inertial>
    </link>

	<!-- Joint properties -->
	<xacro:property name="joint_lower_limit" value="-${3.14}" />
	<xacro:property name="joint_upper_limit" value="${3.14}" />
	<xacro:property name="joint_effort" value="6.0" />
	<xacro:property name="joint_velocity" value="0.524" />

	<!-- Leg macro -->
	<xacro:macro name="leg" params="side position x y angle axis">

		<!-- leg position -->
		<joint name="leg_center_joint_${side}${position}" type="fixed">
			<origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
			<parent link="body_link" />
			<child link="leg_center_${side}${position}" />
		</joint>

		<link name="leg_center_${side}${position}" >
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>

		<!-- coxa -->
		<joint name="coxa_joint_${side}${position}" type="revolute">
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${angle}" />
			<parent link="leg_center_${side}${position}" />
			<child link="coxa_${side}${position}" />
			<axis xyz="0.0 0.0 1.0" />
			<limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
		</joint>
		<transmission name="coxa_transmission_${side}${position}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="coxa_joint_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="coxa_motor_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
        <link name="coxa_${side}${position}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://hexapod_description/meshes/razbot/coxa.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.7 0.7 0.7 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://hexapod_description/meshes/razbot/coxa.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.7 0.7 0.7 1" />
                </material>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>
        <gazebo reference="coxa_${side}${position}">
            <material>Gazebo/DarkGrey</material>
        </gazebo>

		<!-- femur -->
		<joint name="femur_joint_${side}${position}" type="revolute">
			<origin xyz="${coxa_length} 0.0 0.0" rpy="-${pi/2} ${pi/2} 0.0" />
			<parent link="coxa_${side}${position}" />
			<child link="femur_${side}${position}" />
			<axis xyz="0.0 0.0 ${-axis}" />
			<limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
		</joint>
		<transmission name="femur_transmission_${side}${position}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="femur_joint_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="femur_motor_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
        <link name="femur_${side}${position}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://hexapod_description/meshes/razbot/femur.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.7 0.7 0.7 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://hexapod_description/meshes/razbot/femur.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.7 0.7 0.7 1" />
                </material>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>
        <gazebo reference="femur_${side}${position}">
            <material>Gazebo/DarkGrey</material>
        </gazebo>

		<!-- tibia -->
		<joint name="tibia_joint_${side}${position}" type="revolute">
			<origin xyz="-0.004 -${femur_length} 0.0" rpy="${pi} 0.0 0.0" />
			<parent link="femur_${side}${position}" />
			<child link="tibia_${side}${position}" />
			<axis xyz="0.0 0.0 ${axis}" />
			<limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
		</joint>
		<transmission name="tibia_transmission_${side}${position}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="tibia_joint_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="tibia_motor_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
        <link name="tibia_${side}${position}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://hexapod_description/meshes/razbot/tibia.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.7 0.7 0.7 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://hexapod_description/meshes/razbot/tibia.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="">
                    <color rgba="0.7 0.7 0.7 1" />
                </material>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>
        <gazebo reference="tibia_${side}${position}">
            <material>Gazebo/DarkGrey</material>
        </gazebo>

                <!-- foot -->
        <joint name="foot_joint_${side}${position}" type="fixed">
            <origin xyz="${tibia_length} 0.025 0.0" rpy="0.0 0.0 0.0" />
            <parent link="tibia_${side}${position}" />
            <child link="foot_${side}${position}" />
        </joint>
        <link name="foot_${side}${position}">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>
        <gazebo>
            <plugin name="f3d_controller" filename="libgazebo_ros_f3d.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>50</updateRate>
                <bodyName>foot_${side}${position}</bodyName>
                <topicName>${side}${position}_ground_feedback</topicName>
                <frameName>foot_${side}${position}</frameName>
            </plugin>
        </gazebo>

	</xacro:macro>

<!-- Build robot model -->
	<xacro:leg side="R" position="R" x="-${body_length_x/2}" y="-${0.1695/2}" angle="-${5*pi/6}" axis="1" />
	<xacro:leg side="R" position="M" x="0.0" y="-${body_length_y/2}" angle="-${pi/2}" axis="1" />
	<xacro:leg side="R" position="F" x="${body_length_x/2}" y="-${0.1695/2}" angle="-${pi/6}" axis="1" />

	<xacro:leg side="L" position="R" x="-${body_length_x/2}" y="${0.1695/2}" angle="${5*pi/6}" axis="-1" />
	<xacro:leg side="L" position="M" x="0.0" y="${body_length_y/2}" angle="${pi/2}" axis="-1" />
	<xacro:leg side="L" position="F" x="${body_length_x/2}" y="${0.1695/2}" angle="${pi/6}" axis="-1" />

</robot>
